// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/check": {
            "get": {
                "description": "Lookup pemilih (voter) data by NIK using a query parameter.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Voter"
                ],
                "summary": "Check NIK (query)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "NIK",
                        "name": "nik",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Response-check_nik_CheckNIKResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.Response-string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.Response-string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.Response-string"
                        }
                    }
                }
            }
        },
        "/{nik}": {
            "get": {
                "description": "Lookup pemilih (voter) data by NIK using a path parameter.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Voter"
                ],
                "summary": "Check NIK (path)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "NIK",
                        "name": "nik",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Response-check_nik_CheckNIKResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.Response-string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.Response-string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.Response-string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "check_nik.CheckNIKResp": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nik": {
                    "type": "string"
                },
                "nkk": {
                    "type": "string"
                },
                "nrt": {
                    "type": "string"
                },
                "nrw": {
                    "type": "string"
                },
                "subdistrict": {
                    "type": "string"
                },
                "tps_address": {
                    "type": "string"
                },
                "tps_no": {
                    "type": "string"
                }
            }
        },
        "dto.Response-check_nik_CheckNIKResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/check_nik.CheckNIKResp"
                },
                "error": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.Response-string": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "error": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "DPB Online API",
	Description:      "API for checking NIK in the voter database",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
